### ISSUE TITLE
Problem with Restart and Warning script

### ISSUE THREAD

**Issue by ryan1161** [IT07/Game_code#1]
I'm trying to get it to end the mission and it does,  but the variable for the count down thinks it's still at zero after the mission ends and I click continue. How could I fix this to work cause it's on Linux and I want it to wipe the map. Below is what I added

if (_timeLeft < 0) exitWith **{endMission "END1"; };** 

[restart_warnings.zip](https://github.com/IT07/Game_code/files/286838/restart_warnings.zip)

**Comment by IT07** [comment]
Can you provide some more information about "I click continue"?
I need a lot more information about what you are trying to achieve otherwise I can not help you.

**Comment by ryan1161** [comment]
Basically I'm trying to achieve is to have your script end mission which wipes the map of objects and resets loot. But when it ends the mission it comes up with mission complete and that's what I wanted it to do. The problem is right when I hit continue button in-game the server reloads the map and I join in but then mission complete comes up right away. The script still thinks the **_timeleft** is at **0** so it does the **exitwith** which is causing a loop to end the mission every time.

![warning](https://cloud.githubusercontent.com/assets/2374149/15620117/f127e87a-241d-11e6-9435-16b3e9db03b8.png)
![end screen](https://cloud.githubusercontent.com/assets/2374149/15620128/01c1f14e-241e-11e6-94ae-d222f5d3b090.png)

**Comment by ryan1161** [comment]
Never Mind I wrote my own script and now I have a script that I put in my addons to restart the map and play countdown announcer when the timer gets to 5mins.
