### ISSUE TITLE
Error after Restart - Fixes on relog

### ISSUE THREAD

**Issue by ReDBaroN1** [IT07/Game_code#2]
Hi @IT07 

Sorry to necro this but, after a server restart, when I try to access the garage I get this error:
` 1:54:05 Error in expression <hen
{
if not isNull _dsp then
{
_vehs = EPOCH_vgsMyGarage;
if not isNil"_vehs" t>
 1:54:05   Error position: <EPOCH_vgsMyGarage;
if not isNil"_vehs" t>
 1:54:05   Error Undefined variable in expression: epoch_vgsmygarage
 1:54:05 File scarCODE\VGS\functions_VGS\fn_vgsTrash.sqf [SC_fnc_vgsTrash], line 20`
Then the drop down menus in the dialog stop working. If I relog without restarting the server, then it works fine.

Any ideas

**Comment by IT07** [comment]
Hi ReDBaroN1,

I am confused about the function named SC_fnc_vgsTrash....
That function does not exist in my code for the virtual garage.

**Comment by ReDBaroN1** [comment]
Hey @IT07 ,

Thanks for your reply.  The only file I can find mention of it is in scarCODE\VGS\rsc_VGS.hpp

Here is the block:
`class buttonTrash: RscButton
{
	action = "[] spawn SC_fnc_vgsTrash";
	deletable = 0;
	default = 0;
	color[] = {1,1,1,0.9};
	colorActive[] = {0.243,0.388,0.675,1};
	access = 0;
	sizeEx = 0.05;

	idc = 1603;
	text = "DELETE"; //--- ToDo: Localize;
	x = 30.5 * GUI_GRID_W + GUI_GRID_X;
	y = 20.5 * GUI_GRID_H + GUI_GRID_Y;
	w = 9 * GUI_GRID_W;
	h = 2 * GUI_GRID_H;
	colorText[] = {1,1,1,0.8};
	tooltip = "DELETE SELECTED VEHICLE"; //--- ToDo: Localize;
};
`
Thanks for responding.

**Comment by ReDBaroN1** [comment]
The only difference from your code that I have changed is to remove the addaction and dynamic blur in fn_vgsInitClient.sqf as I have moved the action to the epoch dynamic menu (space bar menu) and made it conditional on having a jammer as cursor target. 

Could that have broken this somehow? I can't see why it should and it's odd that everything works flawlessly if you relog. Just won't work until you relog after each server restart......

**Comment by ReDBaroN1** [comment]
The only other change is the fact that epoch already has class cfgFunctions defined in it's own file called the same in a separate configs folder. So I have merged vg's functions into there. But, like I say, everything works after a relog so, I don't think it's this either....

**Comment by ravmustang** [comment]
@ReDBaroN1 
Hey bud, check out #4

**Comment by ReDBaroN1** [comment]
@ravmustang Thanks man. I did manage to fix the issue before but, have seen your updates and will update to that now

**Comment by ravmustang** [comment]
Sounds great Baron, I didn't see this issue until last night.
However to toich on a point in your discussions above, the plot pole requirement is now a config entry as well as max distance from jammer.
